// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/prisma-light/PrismaLightDashboard.tsx": () => import("../components/mockups/prisma-light/PrismaLightDashboard.tsx")
};
